### ISSUE TITLE
Indentation problems?

### ISSUE THREAD

**Issue by dgutov** [pedz/ruby-ts-mode#1]
Hi!

Do you want reports of indentation problems here? A few examples:

```rb
begin
     if true
end
end
```

The second line is not indented at all, because there's no rule for `begin`. The third one is misindented, apparently because `end` is sometimes the "grandchild" of the relevant node to indent to, but sometimes it's the direct child. E.g. for `if` it's a grandchild, and for `begin` it's the direct child.

```rb
foo.bar do |z|
  end
```

Extra offset for `end`.

```rb
foo
.bar do |z|
  end
```

No indentation before `.bar`.

**Comment by pedz** [comment]
Excellent!  Yes.  This will be a good place for bug reports.

**Comment by pedz** [comment]
Is this what you suggest:
```
foo
  .bar do |z|
    dog = 12  
  end
```

or it could be

```
foo
  .bar do |z|
  dog = 12  
end
```

Hmm... I think I like the first one better.  Which is what I have implemented (but having committed yet).

**Comment by dgutov** [comment]
`ruby-mode` does the latter now. See also https://debbugs.gnu.org/cgi/bugreport.cgi?bug=60186#53 where I add a new option to switch to the former behavior.

**Comment by pedz** [comment]
I didn't read the entire thread but I saw this example:
```
  some_variable = 4 +
    some_array.
      reduce do |acc, x|
        acc + x
      end
```

I think I'm going to check in and push some changes.  I've added `ruby-ts-mode-call-block`.  By the way, I'm open to changing most any name I come up with.

The above example is affected by `ruby-ts-mode-call-block` but it is also affect by `ruby-ts-mode-indent-split-exp-by-term`.

I hope you can continue to play with this and point out your thoughts.

**Comment by pedz** [comment]
Oh... I would really like to come up with tests for the indentation part.  The indent rules, to me, seem very fragile.  Changing one thing can affect something else unexpectedly.  It would be nice if I could write a test suite that would I could run through after each change and make sure I'm not going backwards.

Can you point me to some examples of how to do that?

**Comment by dgutov** [comment]
`ruby-mode` in Emacs has a test suite, and most of it is related to indentation. There are two kinds of indentation tests: a number have Ruby code inline, and there are also those which take a file (already in the repo), reindent, and check that the indentation didn't change.

What are your immediate plans for this, BTW? If we put `ruby-ts-mode` side-by-side with `ruby-mode`, we can run most of the tests for both modes.

Like I also said previously, it would be helpful to ensure they are more-or-less compatible WRT indentation and obey the same options. This is compicated by the fact that some new options are not in emacs-29, however.

**Comment by pedz** [comment]
I see the `test/lisp/progmodes/ruby-mode-tests.el`.  I'll see if I can make it work.

> What are your immediate plans for this, BTW?

I'm not sure I understand your question exactly.  My plans are to contribute it to FSF as soon as I can.  I'm waiting for them to sign a document I sent back.  I also need to send them a document stating what I am contributing.  What I have no idea about is how will I make changes to it afterwards, etc.  This is my first rodeo.  I'm not sure that answers your question.

> it would be helpful to ensure they are more-or-less compatible

100% agree.  I think with new tech like this, the entrance fee needs to be minimal or people won't move.  What I'm still not clear on: I'd like to have more options / features but have the defaults set up to match ruby-mode out of the box.  But it isn't clear to me still how that will be received.

> This is compicated by the fact that some new options are not in emacs-29

Yes.  I went grep'ing for `ruby-indent-simplified` in both master and emacs-29 branches and didn't see it.

**Comment by dgutov** [comment]
> I'm not sure I understand your question exactly. My plans are to contribute it to FSF as soon as I can. I'm waiting for them to sign a document I sent back. I also need to send them a document stating what I am contributing. What I have no idea about is how will I make changes to it afterwards, etc. This is my first rodeo. I'm not sure that answers your question.

IIUC if you are in US, the document could be signed electronically? But I suppose there is a delay before the original submission can be processed anyway.

My concern is to understand whether I need to try to push through the addition of the new options to emacs-29, so that ruby-ts-mode could use them instead of reinventing its own ones. Or whether I maybe should try to whip up a minimal TS based mode to include in Emacs if your assignment doesn't make it in time (not sure how to decide, or whether we absolutely have to wait for it to finalize before moving forward; we can ask Eli that).

> 100% agree. I think with new tech like this, the entrance fee needs to be minimal or people won't move. What I'm still not clear on: I'd like to have more options / features but have the defaults set up to match ruby-mode out of the box. But it isn't clear to me still how that will be received.

I think step 1 is to have a patch against ruby-mode.el which adds a new TS-based mode inside it. Using the same conventions (faces, etc) that other `*-ts-mode`-s in the core do, or as close as possible. It won't have all the features you have brewing in this repo now, but we can polish up the basics there: the font-lock rules which look as expected out-of-the-box, and indentation that handles all the cases that ruby-mode does. Or close to that.

Then (maybe as soon as emacs-29 RC is cut) we'll continue development on master. It usually goes like this: first you submit patches for review, one by one, then after that starts to go smoothly and some times passes, the maintainer adds your ssh keys to the project, giving you push access.

I'm going to make ruby-mode.el on master a "core ELPA package", meaning we can have regular updates on ELPA.

Regarding ruby-ts-mode specific options, it shouldn't be a problem. If an option is related to indentation, though, and is supposed to be relatively popular, I think the first step would be to see how hard it is to integrate into ruby-mode. If it's difficult/niche, then ruby-ts-mode is okay. For every feature, I like to understand who are the target audience.

And there is also the question whether the stuff you want to add is specific to Ruby. That navigation code could probably be used with other modes, and so could live somewhere else. A thread on emacs-devel could result in better suggestions.

Worst case, you could have a third-party extension project which contains all the things that didn't make it to the core (yet?).

**Comment by pedz** [comment]
I'm in the US.  The more "harder" document to get through I've signed and it is suppose to be sitting on the director's desk.  I assume it will get signed probably the first week of January when folks get back from vacation.

Let me repeat what you said above in my own words to make sure I'm clear:

If an option can easily be worked into both ruby-mode and ruby-ts-mode, then it would have the same name?  So, option-foo-dog in both modes would change a specific behavior from A to B. 

That's fine with me.  I had just always assumed the options would not use the same names but I can see advantages with using the same name.

> A thread on emacs-devel could result in better suggestions.

https://lists.gnu.org/archive/html/emacs-devel/2022-12/msg01024.html

My interpretation of the resulting suggestion (which I liked) is for folks to go off at this point in time and experiment and see what we come up with.  So far, I am liking my current direction.  It is definitely not specific to Ruby.  I'm not sure how to handle that either since ruby-ts-mode is going to have a keymap.  But should it include things which will eventually get moved or renamed?

I assume you have glanced at ruby-ts-navigation.el and failures.el is also interesting (to me at least ;-)

**Comment by dgutov** [comment]
> I'm in the US. The more "harder" document to get through I've signed and it is suppose to be sitting on the director's desk. I assume it will get signed probably the first week of January when folks get back from vacation.

**Comment by dgutov** [comment]
> I'm in the US. The more "harder" document to get through I've signed and it is suppose to be sitting on the director's desk. I assume it will get signed probably the first week of January when folks get back from vacation.

That sounds good.

> If an option can easily be worked into both ruby-mode and ruby-ts-mode, then it would have the same name? So, option-foo-dog in both modes would change a specific behavior from A to B.

Yes, that's what I meant. We could do it either way, but this seems to be how the core tree-sitter modes do it now. And it can make switching back-and-forth between major modes very seamless.

On the flip side, we'll need those options in there, and Emacs 29 is in feature freeze ;-(

> So far, I am liking my current direction. It is definitely not specific to Ruby. I'm not sure how to handle that either since ruby-ts-mode is going to have a keymap. But should it include things which will eventually get moved or renamed?

If it's not specific to Ruby, then it might go into prog-mode-map instead? Or some keymap common to treesitter modes.

And until that happens, you could always have a minor mode which you'd add to `ruby-ts-mode-hook`.

> I assume you have glanced at ruby-ts-navigation.el and failures.el is also interesting (to me at least ;-)

Not yet. Is it far different from the sexp navigation provided by SMIE?

**Comment by dgutov** [comment]
> And it can make switching back-and-forth between major modes very seamless.

BTW, one other issue regarding indentation options is that `ruby-ts-mode` only refers to them during the major mode setup, but not afterward. That could trip people up. Maybe we should look into dispatching on those values dynamically.

None of the core ts modes do that, so maybe it's not so easy to do.

**Comment by pedz** [comment]
>Not yet. Is it far different from the sexp navigation provided by SMIE?

I think so.  Drew Andrews replied that what I'm doing is close to `thing-at-point` -- which seems true.

> If it's not specific to Ruby, then ...

`treesit.el` currently has two things that look like this:
```
    (keymap-set (current-local-map) "<remap> <beginning-of-defun>"
                #'treesit-beginning-of-defun)
    (keymap-set (current-local-map) "<remap> <end-of-defun>"
                #'treesit-end-of-defun)
```

I was not aware of the `<remap>` feature so perhaps that could be leveraged.

> BTW, one other issue regarding indentation options is that ruby-ts-mode only refers to them during the major mode setup, but not afterward. That could trip people up. Maybe we should look into dispatching on those values dynamically.

In this area, I'm confused by what I am experiencing.  To get some things to take effect, I seem to need to do `ruby-ts-mode` rather than just C-M-x the appropriate values.  Now that I'm thinking about it... perhaps it isn't so mysterious.

These two major pieces are done in `ruby-ts-mode`:
```
  (setq-local treesit-simple-indent-rules (ruby-ts-mode--set-indent-style 'ruby))
  (setq-local treesit-font-lock-settings (ruby-ts-mode--font-lock-settings 'ruby))
```
So, any change to the options is going to need to redo one or both of these expressions since the real meat is in the treesit-* variables.

I think I've seen ways to "watch" if a variable changes and trigger a hook but that might have been just for debugging purposes.

**Comment by dgutov** [comment]
> I was not aware of the <remap> feature so perhaps that could be leveraged.

Yeah, `remap` works in minor mode maps. Here's another example: https://github.com/dgutov/diff-hl/blob/master/diff-hl.el#L795

> So, any change to the options is going to need to redo one or both of these expressions since the real meat is in the treesit-* variables.

Or the predicates used inside the indentation rules would look up the variable values at runtime. I haven't yet looked into how difficult that is to do.

> I think I've seen ways to "watch" if a variable changes and trigger a hook but that might have been just for debugging purposes.

Also an option, but I thought that was more intended for debugging.

**Comment by pedz** [comment]
> Or the predicates used inside the indentation rules would look up the variable values at runtime. I haven't yet looked into how difficult that is to do.

Tthat would not be hard.  Replace the `node-is` or `parent-is`, etc node with a condition that looks at the variable and returns nil appropriately.  I've written `ancestor-is` so I know writing such routines isn't hard.  Well... once you figure out a couple of things which took me a half a day the first time.  So in this case:
```
           ,@(when ruby-ts-mode-indent-split-exp-by-term
               '(((ancestor-is "parenthesized_statements") (ancestor-start "parenthesized_statements") 1)
                 ((ancestor-is "assignment") (ancestor-start "assignment") ruby-ts-mode-indent-offset)))
```
I would modify `ancestor-is`, add an optional argument.  If nil (if the argument isn't specified), the function would act as it does now.  If non-nil, then the function would return nil and effectively disable the rule(s) that use it.  That's the theory at least.

I'm going to review all the face comments and emails and try and get a coherent picture of the changes you are suggesting.  Then I plan to read Info about ERT.

**Comment by dgutov** [comment]
> Tthat would not be hard. Replace the node-is or parent-is, etc node with a condition that looks at the variable and returns nil appropriately. I've written ancestor-is so I know writing such routines isn't hard. Well... once you figure out a couple of things which took me a half a day the first time.

Excellent.

> I would modify ancestor-is, add an optional argument. If nil (if the argument isn't specified), the function would act as it does now. If non-nil, then the function would return nil and effectively disable the rule(s) that use it. That's the theory at least.

It might be more succinct to put the variable check inside the function. And call it `ruby-ts--opindent-ancestor-is`, or something like that.

Also note that all functions that we add to a package must be properly prefixed. With `ruby-`, or `ruby-ts-`.

> I'm going to review all the face comments and emails and try and get a coherent picture of the changes you are suggesting. Then I plan to read Info about ERT.

Cool. Also note that if you start revising a patch against `ruby-mode.el` inside the Emacs repo, it's easy to have the tests run using `ruby-ts-mode`.

**Comment by pedz** [comment]
I loaded ruby-mode-tests.el and ran `ert` and got:
```
Selector: t
Passed:  96
Failed:  2
Skipped: 0
Total:   98/98
```

I guess there are two tests that are expected to fail?

I then made a test directory in this repo, copied ruby-mode-tests.el and ruby-mode-resources over to it and change their names.  For now, I just edited ruby-ts-mode-tests.el and changed the calls to (ruby-mode) to call (ruby-ts-mode).  I have 46 pass, 52 failed and 50 unexpected.  This adds to my guess that two tests are expected to fail.

The first failure I bumped into has to do with `ruby-align-chained-calls` so this will be the start of using ruby-mode's existing options in ruby-ts-mode.  I will also explore looking at the options from within the indent rule.

**Comment by dgutov** [comment]
FWIW, it wouldn't be too terrible for ruby-ts-mode to slightly differ in certain edge cases, as long as the overall default behavior is compatible. Though that would complicate the combined common test suite. But it's better to have it working okay soon than perfect, but much later.

Likewise for obeying the indentation variables -- it's good to have common vars (rather than having a bunch of similar but differently named ones), but it's acceptable for the resulting behaviors to not be 100% the same. We can iron some of such details later.

ruby-mode-tests.el also contains tests for other things, not just indentation. For example, I was looking forward to reimplementing `ruby-add-log-current-method` using tree-sitter, potentially faster and more accurately than the current solution.

**Comment by pedz** [comment]
I'm off on a small tangent.  It started with `ruby-add-log-current-method`.  The Tree Sitter grammar has this for singleton method:

```javascript
    singleton_method: $ => seq(
      'def',
      seq(
        choice(
          field('object', $._variable),
          seq('(', field('object', $._arg), ')')
        ),
        choice('.', '::')
      ),
      $._method_rest
    ),
```

So this passes the Tree Sitter grammar and Ruby 3.1.2 accepts it as well:

```ruby
s = "pie"
g = "apple"
h = nil

def (h = s + g).dog
  "hello"
end

class Hello
  class Doggy
  end

  def Doggy.bark
    "bark"
  end
  
  def (Hello::Doggy).trick
    "banana"
  end
end

puts Hello::Doggy.trick
puts Hello::Doggy.bark
puts h.dog
```

I knew that you could do `def s.meth ...` but didn't know arbitrary expressions were allowed.  I'm not worried about finding the name.  I'm just learning weird edge cases that Ruby has.

**Comment by pedz** [comment]
The tests call `ruby-add-log-current-method` directly instead of calling `add-log-current-defun-function`.

This confused me.  I didn't know how things hung together but I guess `add-log-current-defun-function` is the user interface.  So my version of the tests does `(funcall add-log-current-defun-function)`.

Anyhow... progress (although it's going slower than I had expected.  42 tests to go...
```
Selector: "ruby-add-log-current-method-.*"
Passed:  8
Failed:  0
Skipped: 0
Total:   8/8

Started at:   2022-12-29 12:09:52-0600
Finished.
Finished at:  2022-12-29 12:09:52-0600

........

```

**Comment by dgutov** [comment]
All the examples here seem fixed. :+1: 

The add-log-current-defun-function also works quite well (just checked in a minor fix).
